using Nop.Core;

namespace Nop.Core.Infrastructure;

/// <summary>
/// Represents the default id generator: identifiers are generated by the database
/// (auto-increment / identity columns). This is the standard nopCommerce behaviour.
/// </summary>
public partial class DatabaseIdGenerator : IEntityIdGenerator
{
    #region Properties

    /// <summary>
    /// Gets a value indicating whether identifiers are pre-assigned before insert
    /// </summary>
    public bool PreGenerateIds => false;

    #endregion

    #region Methods

    /// <summary>
    /// Generates the next identifier
    /// </summary>
    /// <returns>The generated identifier</returns>
    public long NextId()
    {
        throw new NopException("Database mode: identifiers are generated by the database, NextId() is not supported");
    }

    #endregion
}
