namespace Nop.Core.Infrastructure;

/// <summary>
/// Represents the entity identifier generator. Implementations decide whether
/// identifiers are generated by the database (auto-increment) or pre-assigned
/// by an external generator before insert.
/// </summary>
public partial interface IEntityIdGenerator
{
    /// <summary>
    /// Gets a value indicating whether identifiers are pre-assigned before insert
    /// (when <see langword="false"/>, the database generates them on insert)
    /// </summary>
    bool PreGenerateIds { get; }

    /// <summary>
    /// Generates the next identifier
    /// </summary>
    /// <returns>The generated identifier</returns>
    long NextId();
}
