using Nop.Core;
using Nop.Core.Configuration;
using Nop.Core.Domain.Configuration;
using Nop.Core.Domain.Topics;
using Nop.Core.Infrastructure;
using Nop.Data;
using Nop.Data.DataProviders;
using NUnit.Framework;

namespace Nop.Tests.Nop.Data.Tests;

/// <summary>
/// Compares the two id generation strategies on SQLite:
///  - Database mode: ids are generated by the database (auto-increment)
///  - Yitter mode: ids are pre-assigned by the yitter generator before insert
/// </summary>
[TestFixture]
public class IdGenerationTests : BaseNopTest
{
    private TestEntityIdGenerator _generator;

    [SetUp]
    public void Setup()
    {
        _generator = GetService<IEntityIdGenerator>() as TestEntityIdGenerator
                     ?? throw new NopException("TestEntityIdGenerator is not registered");
    }

    [TearDown]
    public void Teardown()
    {
        //the generator is a shared singleton: restore the database strategy so the
        //other test fixtures are not affected by the pre-assigned strategies
        _generator?.UseDatabase();
    }

    private async Task<Setting> InsertSettingAsync(string name)
    {
        var repository = GetService<IRepository<Setting>>();
        var setting = new Setting { Name = name, Value = "1" };
        await repository.InsertAsync(setting);

        return setting;
    }

    [Test]
    public async Task DatabaseMode_UsesDatabaseIdentity()
    {
        _generator.UseDatabase();
        Assert.That(_generator.PreGenerateIds, Is.False);

        //insert two entities: ids must be consecutive values generated by the database
        var s1 = await InsertSettingAsync($"idtest.db.{Guid.NewGuid():N}");
        var s2 = await InsertSettingAsync($"idtest.db.{Guid.NewGuid():N}");

        Assert.That(s1.Id, Is.GreaterThan(0));
        Assert.That(s2.Id, Is.EqualTo(s1.Id + 1), "Database mode must generate consecutive auto-increment ids");
    }

    [Test]
    public async Task YitterMode_UsesPreAssignedIds()
    {
        //base time = now so the yitter ids stay inside the Int32 range
        _generator.UseYitter(new IdGenerationConfig
        {
            YitterWorkerId = 1,
            YitterSeqBitLength = 12,
            YitterBaseTime = DateTime.UtcNow.ToString("O")
        });
        Assert.That(_generator.PreGenerateIds, Is.True);

        //insert two entities: ids must be pre-assigned by yitter and unique
        //(note: within the same millisecond yitter sequence numbers are
        //consecutive, so ids may look sequential - that is expected)
        var s1 = await InsertSettingAsync($"idtest.yitter.{Guid.NewGuid():N}");
        var s2 = await InsertSettingAsync($"idtest.yitter.{Guid.NewGuid():N}");

        Assert.That(s1.Id, Is.GreaterThan(0));
        Assert.That(s2.Id, Is.GreaterThan(0));
        Assert.That(s1.Id, Is.Not.EqualTo(s2.Id), "Yitter ids must be unique");
    }

    [Test]
    public async Task YitterMode_IdsAreGloballyUniqueAcrossTables()
    {
        //database identity is per-table (each table restarts from 1), while yitter
        //ids are globally unique across all tables - verify inserts into two
        //different tables never produce colliding ids
        _generator.UseYitter(new IdGenerationConfig
        {
            YitterWorkerId = 1,
            YitterSeqBitLength = 12,
            YitterBaseTime = DateTime.UtcNow.ToString("O")
        });

        var setting = await InsertSettingAsync($"idtest.yitter.x.{Guid.NewGuid():N}");
        var topicRepository = GetService<IRepository<Topic>>();
        var topic = new Topic { Title = $"idtest-yitter-{Guid.NewGuid():N}", Body = "x" };
        await topicRepository.InsertAsync(topic);

        Assert.That(topic.Id, Is.GreaterThan(0));
        Assert.That(topic.Id, Is.Not.EqualTo(setting.Id), "Yitter ids must be globally unique across tables");
    }

    [Test]
    public async Task TinyidMode_UsesPreAssignedSegments()
    {
        //start the tinyid segment high enough to avoid colliding with the ids of
        //the sample data already present in the tables. NOTE: the segment table is
        //shared across tests, so the actual starting id may be higher than the
        //configured start id (the segment only moves forward) - what matters is
        //that ids are pre-assigned sequentially from the segment
        const long startId = 1_000_000;
        _generator.UseTinyid(new IdGenerationConfig { TinyidStep = 10000, TinyidStartId = startId });
        Assert.That(_generator.PreGenerateIds, Is.True);

        //insert two entities: ids must be pre-assigned from the tinyid segment
        var s1 = await InsertSettingAsync($"idtest.tinyid.{Guid.NewGuid():N}");
        var s2 = await InsertSettingAsync($"idtest.tinyid.{Guid.NewGuid():N}");

        Assert.That(s1.Id, Is.GreaterThan(startId), "Tinyid ids start after the configured start id");
        Assert.That(s2.Id, Is.EqualTo(s1.Id + 1), "Tinyid ids must be sequential from the segment");
    }

    [Test]
    public async Task TinyidMode_AllocatesDisjointSegmentsAcrossInstances()
    {
        const long startId = 2_000_000;
        _generator.UseTinyid(new IdGenerationConfig { TinyidStep = 10, TinyidStartId = startId });

        //simulate a second instance with its own generator: both must receive
        //disjoint id ranges from the database segment allocator
        var second = new TinyidIdGenerator(new IdGenerationConfig { TinyidStep = 10, TinyidStartId = startId });
        var secondGenerator = new TestEntityIdGenerator();
        secondGenerator.UseTinyid(new IdGenerationConfig { TinyidStep = 10, TinyidStartId = startId });

        var ids1 = new List<int>();
        var ids2 = new List<int>();
        for (var i = 0; i < 5; i++)
        {
            ids1.Add(_generator.NextId());
            ids2.Add(second.NextId());
            ids2.Add(secondGenerator.NextId());
        }

        Assert.That(ids1.Distinct().Count(), Is.EqualTo(ids1.Count), "First instance ids must be unique");
        Assert.That(ids2.Distinct().Count(), Is.EqualTo(ids2.Count), "Second instance ids must be unique");
        Assert.That(ids1.Intersect(ids2).Any(), Is.False, "Segments from concurrent instances must not overlap");
    }
}
