using Nop.Core.Configuration;

namespace Nop.Core.Configuration;

/// <summary>
/// Represents the identifier generation mode
/// </summary>
public enum IdGenerationMode
{
    /// <summary>
    /// Identifiers are generated by the database (auto-increment/identity columns). Default.
    /// </summary>
    Database = 0,

    /// <summary>
    /// Identifiers are pre-assigned by the Yitter high-performance id generator
    /// (https://github.com/yitter/IdGenerator) before the entity is inserted.
    /// NOTE: yitter generates 64-bit ids; nopCommerce entities currently use
    /// Int32 ids, so ids must fit into Int32 (see YitterIdGenerator).
    /// </summary>
    Yitter = 1,

    /// <summary>
    /// Identifiers are pre-assigned from a Tinyid-style segment
    /// (https://github.com/didi/tinyid): a database backed number segment
    /// allocator. Ids are sequential Int32 values, so this mode is fully
    /// compatible with nopCommerce entities and works across instances.
    /// </summary>
    Tinyid = 2
}

/// <summary>
/// Represents settings for the entity identifier generation strategy.
/// Implements <see cref="IConfig"/> so it can be managed from appsettings.json
/// (section "IdGenerationConfig"), and <see cref="ISettings"/> so it can also be
/// stored/managed in the database settings table in the future.
/// </summary>
public partial class IdGenerationConfig : IConfig, ISettings
{
    /// <summary>
    /// Gets a section name to load configuration
    /// </summary>
    public string Name => GetType().Name;

    /// <summary>
    /// Gets an order of configuration
    /// </summary>
    public int Order => 10;

    /// <summary>
    /// Gets or sets the identifier generation mode
    /// </summary>
    public int IdGenerationMode { get; set; } = (int)Nop.Core.Configuration.IdGenerationMode.Database;

    /// <summary>
    /// Gets or sets the yitter worker id (0-65535)
    /// </summary>
    public int YitterWorkerId { get; set; }

    /// <summary>
    /// Gets or sets the yitter sequence bit length (default 12)
    /// </summary>
    public int YitterSeqBitLength { get; set; } = 12;

    /// <summary>
    /// Gets or sets the yitter base time (ISO-8601 string). yitter generates 64-bit ids;
    /// nopCommerce entities use Int32 ids, so keep the base time close to the current
    /// time to keep generated ids inside Int32. Leave empty for the yitter default.
    /// </summary>
    public string YitterBaseTime { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the tinyid segment size (how many ids are fetched from the
    /// database in one round-trip, default 10000)
    /// </summary>
    public int TinyidStep { get; set; } = 10000;

    /// <summary>
    /// Gets or sets the tinyid initial id (the first generated id = start + 1,
    /// default 0, i.e. ids start from 1)
    /// </summary>
    public long TinyidStartId { get; set; }
}
